spring.application.name=events

#1 username of database
spring.datasource.username = root

#2 password of database
spring.datasource.password = HalJordan83#

#3 url of database
spring.datasource.url = jdbc:mysql://localhost:3306/db_events

#4 dialect of database
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

#5 debug
spring.jpa.show-sql=true

#6 criação das tabelas
spring.jpa.hibernate.ddl-auto=update